#!/usr/bin/python3
import sys


def _prime(n):
    if n < 2:
        return False
    for j in range(2, int(n**0.5) + 1):
        if n % j == 0:
            return False
    return True


def factorize(n):
    for j in range(2, int(n**0.5) + 1):
        if n % j == 0 and _prime(j):
            larger = n // j
            if _prime(larger):
                return j, larger
    return None


def main(path_f):
    with open(path_f, 'r') as file:
        n = int(file.read().strip())

    fac = factorize(n)
    if fac:
        print(f"{n}={fac[1]}*{fac[0]}")
    else:
        print(f"Unable to factorize {n} into prime numbers")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        sys.exit(1)

    path_f = sys.argv[1]
    main(path_f)
